[project]
name = "guitar-cv-amt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch>=2.8.0",
]

[project.optional-dependencies]
transcription = [
    "mt3-infer[torch] @ git+https://github.com/openmirlab/mt3-infer.git ; python_version >= '3.10'",
    "music21",
    "yt-dlp",
]
